export default {
  name: 'vinted',
  displayName: 'Vinted',
  baseUrl: 'https://www.vinted.fr',
  apiUrl: 'https://www.vinted.fr/api/v2/catalog/items',
  enabled: true,
  region: 'fr',
  country: 'France',
  currency: 'EUR',
  rateLimit: { requests: 5, period: 1000 },
  timeout: 15000,
  requiresAuth: false,
  requiresCookies: true,
  // Vinted has multiple regional domains
  regionalDomains: {
    fr: 'https://www.vinted.fr',
    es: 'https://www.vinted.es',
    de: 'https://www.vinted.de',
    it: 'https://www.vinted.it',
    pt: 'https://www.vinted.pt',
    pl: 'https://www.vinted.pl',
    uk: 'https://www.vinted.co.uk',
    nl: 'https://www.vinted.nl',
    be: 'https://www.vinted.be',
    lt: 'https://www.vinted.lt',
    cz: 'https://www.vinted.cz',
    at: 'https://www.vinted.at',
  },
};
